export enum PokemonType {
  Grass = "草",
  Poison = "毒",
  Fire = "火",
  Water = "水",
  Normal = "一般",
  Flying = "飛行",
  Electric = "電",
  Ground = "地面",
  Fairy = "妖精",
  Psychic = "超能力",
  Fighting = "格鬥",
  Rock = "岩石",
  Ice = "冰",
  Dragon = "龍",
  Steel = "鋼",
  Ghost = "幽靈",
  Bug = "昆蟲",
  Dark = "暗黑",
}

// ✅ 類型對應的顏色
export const PokemonTypeColors: Record<PokemonType, string> = {
  [PokemonType.Grass]: "#78C850",
  [PokemonType.Poison]: "#A040A0",
  [PokemonType.Fire]: "#F08030",
  [PokemonType.Water]: "#6890F0",
  [PokemonType.Normal]: "#A8A878",
  [PokemonType.Flying]: "#A890F0",
  [PokemonType.Electric]: "#F8D030",
  [PokemonType.Ground]: "#E0C068",
  [PokemonType.Fairy]: "#EE99AC",
  [PokemonType.Psychic]: "#F85888",
  [PokemonType.Fighting]: "#C03028",
  [PokemonType.Rock]: "#B8A038",
  [PokemonType.Ice]: "#98D8D8",
  [PokemonType.Dragon]: "#7038F8",
  [PokemonType.Steel]: "#B8B8D0",
  [PokemonType.Ghost]: "#705898",
  [PokemonType.Bug]: "#A8B820",
  [PokemonType.Dark]: "#705848",
};
